--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/yamlcomments
build-by-default: true
branches:
- dev
projects:
  yamlcomments:
    path: ""
    model: virion
    type: library
...
